# settings.py
import os
from pathlib import Path

"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(1v^tkjw7poj*)w88xz33c+_v#p#ooav+g%5^(5it5z62f-ll('

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True  # Old setting
# Set to False for production!
DEBUG = False 

# When DEBUG is False, you must configure ALLOWED_HOSTS.
# For local testing, '127.0.0.1' and 'localhost' are sufficient.
# For deployment, you'd add your domain names.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost'] # Add your production domain names here later


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    'practice_relationships',
    'accounts',
    'csp', # Add this for Content Security Policy
]

AUTH_USER_MODEL = 'bookshelf.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware', # Add this line for Content Security Policy, ideally after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # This is for X_FRAME_OPTIONS, can be kept
]

ROOT_URLCONF = 'LibraryProject.urls'

# LibraryProject/LibraryProject/settings.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Ensure this line is present and correctly points to your project's root 'templates' folder
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Addis_Ababa'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LibraryProject/LibraryProject/settings.py

# ... (other settings above) ...

STATIC_URL = 'static/'
LOGIN_REDIRECT_URL = "/accounts/profile/"
LOGOUT_REDIRECT_URL = "/accounts/profile/"

# This is crucial for Django to find static files in your apps and custom directories
STATICFILES_DIRS = [
    # This first entry is common for project-wide static files (e.g., LibraryProject/static/)
    os.path.join(BASE_DIR, 'static'),
    # This entry tells Django to look for static files inside your 'practice_relationships' app's static directory
    # specifically in 'LibraryProject/practice_relationships/static/'
    os.path.join(BASE_DIR, 'practice_relationships', 'static'),
]

# This is where Django will collect all static files when you run 'python manage.py collectstatic'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LibraryProject/LibraryProject/settings.py

# ... (other settings above) ...

# Email configuration for password reset (Development only)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 1025
DEFAULT_FROM_EMAIL = 'webmaster@yourdomain.com'
SERVER_EMAIL = 'webmaster@yourdomain.com'

# XSS, Clickjacking, and MIME-sniffing protections
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY' # Prevents clickjacking by forbidding embedding in iframes
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enforce that cookies are only sent over HTTPS.
# For local development without HTTPS, setting these to True will prevent your application from working
# because your browser won't send the cookies.
# For the deliverable, set them to True.
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Recommended for production over HTTPS
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000 # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Content Security Policy (CSP)
# A strict policy as a starting point. Adjust as needed for your project's assets.
CSP_DEFAULT_SRC = ("'self'",) # Allow content from same origin
CSP_SCRIPT_SRC = ("'self'",) # Allow scripts from same origin
CSP_STYLE_SRC = ("'self'",) # Allow stylesheets from same origin
CSP_IMG_SRC = ("'self'",) # Allow images from same origin
CSP_FONT_SRC = ("'self'",) # Allow fonts from same origin
CSP_CONNECT_SRC = ("'self'",) # Allow connections (XHR, WebSockets) from same origin
CSP_BASE_URI = ("'self'",) # Disallows any <base> tag that doesn't match the current origin
CSP_OBJECT_SRC = ("'none'",) # Disallow plugins like <object>, <embed>, or <applet>
CSP_FRAME_ANCESTORS = ("'self'",) # Controls embedding of your site in iframes
CSP_FORM_ACTION = ("'self'",) # Restricts which URLs can be used as the action for HTML form submissions
CSP_REPORT_URI = None # Optional: URL to send CSP violation reports (e.g., to Sentry)
# CSP_REPORT_ONLY = DEBUG # Set to True in development to log violations without blocking

# Example for external CDN resources (uncomment and adjust if needed):
# CSP_SCRIPT_SRC = ("'self'", "https://cdn.jsdelivr.net", "https://code.jquery.com")
# CSP_STYLE_SRC = ("'self'", "https://cdn.jsdelivr.net")