# Generated by Django 5.1.6 on 2025-07-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view_book', 'Can view book data'), ('can_create_book', 'Can create new books'), ('can_edit_book', 'Can edit existing books'), ('can_delete_book', 'Can delete a book')], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
