"""
Django settings for temp_project project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os # Make sure os is imported for os.path.join

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h^aag3ia&tm8@7t3+x&_v1w@rn3fwp47@o#!8eq0-nbo-fc5*9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # For development, keep True. For production, set to False.

ALLOWED_HOSTS = [] # In production, this should contain your domain names, e.g., ['yourdomain.com', 'www.yourdomain.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Your custom apps go here
    'bookshelf',
    'practice_relationships',
    'accounts',
