# ~/Alx_DjangoLearnLab/api_project/api/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
# ONLY import BookViewSet. Remove 'BookList' if it's there.
from .views import BookViewSet

# Create a router instance
router = DefaultRouter()

# Register your BookViewSet with the router
router.register(r'books_all', BookViewSet, basename='book_all')

urlpatterns = [
    # This line for BookList MUST BE GONE or commented out
    # If you still have: path('books/', BookList.as_view(), name='book-list'),
    # REMOVE it or change it to: # path('books/', BookList.as_view(), name='book-list'),

    # This line includes all routes generated by the router
    path('', include(router.urls)),
]